
server:
  #port: 8083 # usa el valor de PORT (de Cloud Run) o 8083 si no está definido
  port: ${PORT:8083}

spring:
  config:
    import: classpath:error-catalog.yml
  data:
    mongodb:
      uri: mongodb+srv://mongoAdmin:C0sm0%23Secure2024%21@mongo-clinica-prd.global.mongocluster.cosmos.azure.com/bdclinica?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000

task:
    api-server-url: https://clinica365-services-cumppwkd3q-uc.a.run.app  # Valor por defecto para entorno local

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    display-request-duration: true
    try-it-out-enabled: true
    packages-to-scan: com.task.services.v1.task.controller
  default-produces-media-type: application/json
